"""add analytics tables

Revision ID: dfcad66dd02f
Revises: 0003
Create Date: 2026-10-01 11:10:26.534119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcad66dd02f'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_insights_document_id'), 'document_insights', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_insights_id'), 'document_insights', ['id'], unique=False)
    op.create_index(op.f('ix_document_insights_user_id'), 'document_insights', ['user_id'], unique=False)
    op.create_table('extracted_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('category_value', sa.String(length=500), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('chart_type', sa.String(length=50), nullable=False),
    sa.Column('is_timeseries', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_data_document_id'), 'extracted_data', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_data_id'), 'extracted_data', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_data_user_id'), 'extracted_data', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_data_user_id'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_id'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_document_id'), table_name='extracted_data')
    op.drop_table('extracted_data')
    op.drop_index(op.f('ix_document_insights_user_id'), table_name='document_insights')
    op.drop_index(op.f('ix_document_insights_id'), table_name='document_insights')
    op.drop_index(op.f('ix_document_insights_document_id'), table_name='document_insights')
    op.drop_table('document_insights')
    # ### end Alembic commands ###
